name: Build and push
on: push
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pus-nais-java-app
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and push Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker build -t ${IMAGE}:java8 java-8
          docker build -t ${IMAGE}:java11 java-11
          docker build -t ${IMAGE}:java13 java-13
          docker build -t ${IMAGE}:java15 java-15
          docker push ${IMAGE}
